### PR TITLE
Fix nullpointer dereference in Find()

### PR DESCRIPTION
**Pull request by Freeaqingme**
I ran into this stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43eeac]

goroutine 1 [running]:
github.com/weppos/publicsuffix-go/publicsuffix.(*Rule).Decompose(0x0, 0x7391d0, 0x12, 0x0, 0x0, 0x0, 0x0)
/home/dolf/Projects/Cluegetter/src/github.com/weppos/publicsuffix-go/publicsuffix/publicsuffix.go:263 +0x6c
github.com/weppos/publicsuffix-go/publicsuffix.ParseFromListWithOptions(0xc20801e4c0, 0x7391d0, 0x12, 0xc208171f80, 0x6, 0x0, 0x0)
/home/dolf/Projects/Cluegetter/src/github.com/weppos/publicsuffix-go/publicsuffix/publicsuffix.go:409 +0x102
github.com/weppos/publicsuffix-go/publicsuffix.DomainFromListWithOptions(0xc20801e4c0, 0x7391d0, 0x12, 0xc208171f80, 0x0, 0x0, 0x0, 0x0)
/home/dolf/Projects/Cluegetter/src/github.com/weppos/publicsuffix-go/publicsuffix/publicsuffix.go:379 +0x73
main.main()
/home/dolf/Projects/Cluegetter/test2.go:7 +0x6b
```

That could be reproduced by this piece of code (derived from the README), when using a TLD that isn't known. Which happens to be
seen some times on mail servers where people just use any kind of interesting names.

```
package main

import "github.com/weppos/publicsuffix-go/publicsuffix"

func main() {
   publicsuffix.DomainFromListWithOptions(publicsuffix.DefaultList, foobar.localdomain, &publicsuffix.FindOptions{IgnorePrivate: true})
}
```

### CODE REVIEW

**Comment by weppos** [comment]
Thanks for the report @Freeaqingme. Actually, I'm not sure this is a real bug. If you provide a custom `FindOption`, you are responsible for passing all the appropriate options.

```go
func main() {
   publicsuffix.DomainFromListWithOptions(publicsuffix.DefaultList, foobar.localdomain, &publicsuffix.FindOptions{IgnorePrivate: true, DefaultRule: publicsuffix.DefaultRule})
}
```

In fact, there are cases where you want the default rule to be nil (for example because you want to skip the `*` default rule that doesn't allow you to validate whether a given hostname belongs to a "valid" TLD).

Merging the patch you propose will invalidate this use case. Therefore, I don't think I'll merge it.

However, I will be happy to merge the README changes if you provide a separate PR. I will also happily merge any documentation improvement to either the `FindOptions` or `Find`, that makes it more clear the expected behavior of when you provide custom find options.

**Comment by Freeaqingme** [comment]
I'm all for providing flexibility and educating your users. However, how does this invalidate any use case? What it's meant to fix is a panic. Not change any other behavior. If you'd prefer, we could also return nil instead of the default rule?

**Comment by weppos** [comment]
It does, because if I execute this call

```
func main() {
   publicsuffix.DefaultList.Find(foobar.localdomain, &publicsuffix.FindOptions{ IgnorePrivate: true, DefaultRule: nil })
}
```

I expect it to return `nil`. After your change, it will return the `DefaultRule`.

In fact, I believe the bug is in the `ParseFromListWithOptions`, where I should check for the rule returned from

```
r := l.Find(n, options)
```

>  If you'd prefer, we could also return nil instead of the default rule?

It would still cause the error. You can create a test case to validate my assertion. In fact, in any case, we need to add a test case in order to merge this patch as it was clearly missing a proper test.

Actually, we should probably have 2 test cases: 1 for `Find`, where we ensure that the behavior I mentioned is not replacced (as your change to `Find` would have introduced a different bug), and one for `ParseFromListWithOptions` to make sure it returns nil without attempting to decompose the rule, when the rule is nil.

**Comment by Freeaqingme** [comment]
Thanks @weppos !

**Pull request closed without merging**
